### PR TITLE
Convert Travis to GHA

### PR DESCRIPTION
**Pull request by christopher-dG**

### CODE REVIEW

**Comment by ararslan** [comment]
Is it expected that there's no Codecov status showing up?

**Comment by christopher-dG** [comment]
Hm, not quite sure. It did get published [here](https://app.codecov.io/gh/beacon-biosignals/SerializationCaches.jl/branch/cdg%2Fgha/) at least, but I'm not sure if there should be a comment posted here.

**Comment by ararslan** [comment]
I think we disable comments but want the PR status indicator alongside the GHA statuses. We had that with Travis, IIRC.

**Comment by christopher-dG** [comment]
Last commit might help, based on [this line](https://github.com/beacon-biosignals/SerializationCaches.jl/runs/2041168460?check_suite_focus=true#step:8:29)

**Comment by ararslan** [comment]
Looks like that did it. Can you make sure we have that in all of them so that we still get the Codecov statuses?

**Review by ararslan — APPROVED** [review]

**Pull request merged**
